apiVersion: v1
kind: List
metadata:
  name: data-consumer
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        application: quarkus-bbt
      name: data-consumer


  - apiVersion: v1
    kind: DeploymentConfig

    metadata:
      labels:
        application: quarkus-bbt
      name: data-consumer
    spec:
      replicas: 1
      selector:
        detploymentConfig: data-consumer
      strategy:
        activeDeadlineSeconds: 1200
        rollingParams:
          maxSurge: 0
          maxUnavailable: 1
        type: Rolling
      template:
        metadata:
          labels:
            application: quarkus-bbt
            deploymentConfig: data-consumer
        spec:
          containers:
            - image: data-consumer
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              name: data-consumer
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 1
                  memory: 1Gi
                requests:
                  cpu: 50m
                  memory: 100Mi
      trigger:
        - imageChangeParams:
            automatic: true
            containerNames:
              - data-consumer
            from:
              kind: ImageStreamTag
              name: data-consumer:latest
          type: ImageChange
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: quarkus-bbt
      name: data-consumer
    spec:
      ports:
        - name: data-consumer-http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentConfig: data-consumer
      sessionAffinity: None
      type: ClusterIP
